language: java
before_install: chmod +x gradlew
install: true
matrix:
  include:
    - jdk: oraclejdk8
script: ./gradlew clean :lib:jar
deploy:
  provider: releases
  api_key:
    secure: "BJDoKkSJsFGT6rGEk+cVBFci2gSlIxWe0BqWtBMXM5qAWTT+cQkcESuEEobO/3s/Ba+2/+2nUycPFHjWAaRVbcFbOS97AA1iywrZiSQ+UjAl1tu3oHqYH2WKZXWIxDfjwc/pvyeWlLWgDHEDZwmQUF2EXUn6AW0Q4KIoaWGdFzrJvL+JUPqXyfE40EPBoml5hOTtLES9K2zsChZXIzPkjSWkqQMcgenRwxirGwjGiI28nY5RXosuMpcDJ1OzJSFUzuth04QRmpr/+XjldF2b6t+qWeuAuAx5mPQtjHdLR7AMPzmlbuyf7sUCMcEWCwbRTkkavtFECc6KJOmQ/B8sFiuwRERWbv4papSnZCgr8U/W1XIVoaoJ9a7hGl710CFT9Sv4MODHNvQ/zSRwYfbpwOBuGSkS+S6U8OwCfIjrt1DsE9800jcnj5E65qfkAzAN1t+zFBtjOJNykTW11yyrvoQ2YN/8VcF4wSvzEtotvMbtvOH8ONL2BpscmJr/NsZWrLrELjB1GvxEZIMP3s4VNZ7hAyY2SAmU9OGddoVjxf5Tc0ScUFKEPNhW7L2HB9pjMUu8h0Ip56KgUCOj6oQbkDale1VTH2zBtsGvN0/qgzXBAW1KhpLO6/dU6rXkeKqlhAxH+S1j7MJ3V/hvgaWihokj8CcytgX0LTbpSTt4NcA="
  file: lib/build/libs/replay-kt-*
  skip_cleanup: true
  file_glob: true
  on:
    tags: true
    branch: master