name: Create release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: thecodemonkey/action-get-gradle-version@master
        id: version
      - run: chmod +x gradlew
      - run: ./gradlew clean :lib:jar
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.version.outputs.version }}
          files: lib/build/libs/replay-kt-*
          generate_release_notes: true
